### ISSUE TITLE
How do you actually Install this thing?

### ISSUE THREAD

**Issue by coltonisgod234** [TodePond/DreamBerd#464]
i'm not even joking.
how though?

**Comment by Coletronix** [comment]
No problem, it runs quite efficiently in ChatGPT

**Comment by coltonisgod234** [comment]
lol

**Comment by FlareFlo** [comment]
Using the installer installer of course

**Comment by coltonisgod234** [comment]
> Using the installer installer of course

You need to install the installer installer with the installer installer installer

**Comment by james-cnz** [comment]
Yeah, I think it's vapourware.  Re ChatGPT, see:
https://github.com/TodePond/DreamBerd/blob/main/README.md#compiling
But, like it says, I haven't had much luck with this (at least not with ChatGPT 3).

**Comment by restush** [comment]
There is gui somewhere in the git. You need download that then install the installer using CMD. It will make new window, then it will downloading the DreamBerd assembly. After finish, you can test using this code.

```
const const name = "Luke"!
print(name)!
```

Please be careful using the gui because it may have green of death when error occured.
![image](https://github.com/TodePond/DreamBerd---e-acc/assets/44837900/b41716a8-903e-46ce-b540-3fd425bf0eac)


I recommended using ChatGPT to compile.

**Comment by coltonisgod234** [comment]
Okay! Thanks It worked!
